version: '3.9'

services:
  frontend:
    image: node:18
    restart: always

  backend:
    image: node:18
    restart: always

  nginx:
    image: nginx
    restart: always

  postgres:
    image: postgres
    restart: always

  redis:
    image: redis
    restart: always